# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RMS News
email: 
description: > # this means to ignore newlines until "baseurl:"
  The Randolph Middle School Newspaper Club's Official Jekyll Blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rmsnews.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username: RMSNews

# Build settings
markdown: CommonMarkGhPages

theme: jekyll-theme-architect
